//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Limnor Studio.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefaultNamespace
{
    using System;
    using System.Xml;
    using System.Text;
    using System.Collections.Generic;
    using Limnor.Drawing2D;
    using System.Drawing;
    using System.Windows.Forms;
    using Limnor.Net;
    using LimnorDatabase;
    using System.Data.OleDb;
    using System.Data;
    
    public class CreateNewUser : Limnor.Drawing2D.DrawingPage
    {
        protected internal System.Windows.Forms.Label Label1;
        protected internal System.Windows.Forms.PictureBox PictureBox1;
        protected internal System.Windows.Forms.Label LabelLNM;
        protected internal System.Windows.Forms.Label LabelSTATE;
        protected internal System.Windows.Forms.Label LabelCONTACT;
        protected internal System.Windows.Forms.Label LabelLOGIN;
        protected internal System.Windows.Forms.Label LabelFNM;
        protected internal System.Windows.Forms.Label LabelLEVEL;
        protected internal System.Windows.Forms.Label LabelEMAIL;
        protected internal System.Windows.Forms.TextBox TextBoxLNM;
        protected internal System.Windows.Forms.TextBox TextBoxSTATE;
        protected internal System.Windows.Forms.TextBox TextBoxCONTACT;
        protected internal System.Windows.Forms.TextBox TextBoxEMAIL;
        protected internal System.Windows.Forms.TextBox TextBoxLOGIN;
        protected internal System.Windows.Forms.TextBox TextBoxLEVEL;
        protected internal System.Windows.Forms.TextBox TextBoxFNM;
        protected internal System.Windows.Forms.Button ButtonCREATE;
        protected internal System.Windows.Forms.Label LabelMSG;
        protected internal LimnorDatabase.EasyUpdator EasyUpdator1;
        private System.ComponentModel.IContainer components;
        protected internal LimnorDatabase.EasyDataSet EasyDataSet1;
        protected internal LimnorDatabase.WebLoginManager WebLoginManager1;
        protected internal Limnor.Net.MailSender MailSender1;
        private static CreateNewUser _DefaultForm;
        private string valueOfNewPassword;
        /// <summary>
        /// </summary>
        public CreateNewUser()
        {
            this.InitializeComponent();
        }
        public static CreateNewUser DefaultForm
        {
            get
            {
                if (((_DefaultForm == null) 
                            || (_DefaultForm.IsDisposed || _DefaultForm.Disposing)))
                {
                    _DefaultForm = new CreateNewUser();
                }
                return _DefaultForm;
            }
        }
        public virtual string NewPassword
        {
            get
            {
                return this.valueOfNewPassword;
            }
            set
            {
                this.valueOfNewPassword = value;
            }
        }
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(CreateNewUser));
            LimnorDatabase.SQLNoneQuery sqlnonequery1 = new LimnorDatabase.SQLNoneQuery();
            LimnorDatabase.DbParameterListExt dbparameterlistext1 = new LimnorDatabase.DbParameterListExt();
            this.Label1 = new System.Windows.Forms.Label();
            this.PictureBox1 = new System.Windows.Forms.PictureBox();
            this.LabelLNM = new System.Windows.Forms.Label();
            this.LabelSTATE = new System.Windows.Forms.Label();
            this.LabelCONTACT = new System.Windows.Forms.Label();
            this.LabelLOGIN = new System.Windows.Forms.Label();
            this.LabelFNM = new System.Windows.Forms.Label();
            this.LabelLEVEL = new System.Windows.Forms.Label();
            this.LabelEMAIL = new System.Windows.Forms.Label();
            this.TextBoxLNM = new System.Windows.Forms.TextBox();
            this.TextBoxSTATE = new System.Windows.Forms.TextBox();
            this.TextBoxCONTACT = new System.Windows.Forms.TextBox();
            this.TextBoxEMAIL = new System.Windows.Forms.TextBox();
            this.TextBoxLOGIN = new System.Windows.Forms.TextBox();
            this.TextBoxLEVEL = new System.Windows.Forms.TextBox();
            this.TextBoxFNM = new System.Windows.Forms.TextBox();
            this.ButtonCREATE = new System.Windows.Forms.Button();
            this.LabelMSG = new System.Windows.Forms.Label();
            this.components = new System.ComponentModel.Container();
            this.EasyUpdator1 = new LimnorDatabase.EasyUpdator(this.components);
            this.EasyDataSet1 = new LimnorDatabase.EasyDataSet();
            this.WebLoginManager1 = new LimnorDatabase.WebLoginManager(this.components);
            this.MailSender1 = new Limnor.Net.MailSender();
            ((System.ComponentModel.ISupportInitialize)(EasyDataSet1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(PictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // Label1
            // 
            this.Label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.Label1.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.Label1.Location = new System.Drawing.Point(158, 27);
            this.Label1.Name = "Label1";
            this.Label1.Size = new System.Drawing.Size(111, 23);
            this.Label1.TabIndex = 0;
            this.Label1.Text = "NEW USER";
            // 
            // PictureBox1
            // 
            this.PictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("PictureBox1.Image")));
            this.PictureBox1.Location = new System.Drawing.Point(175, 53);
            this.PictureBox1.Name = "PictureBox1";
            this.PictureBox1.Size = new System.Drawing.Size(64, 44);
            this.PictureBox1.TabIndex = 1;
            this.PictureBox1.TabStop = false;
            // 
            // LabelLNM
            // 
            this.LabelLNM.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.LabelLNM.ForeColor = System.Drawing.Color.Navy;
            this.LabelLNM.Location = new System.Drawing.Point(31, 168);
            this.LabelLNM.Name = "LabelLNM";
            this.LabelLNM.Size = new System.Drawing.Size(121, 23);
            this.LabelLNM.TabIndex = 2;
            this.LabelLNM.Text = "   LAST NAME";
            // 
            // LabelSTATE
            // 
            this.LabelSTATE.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.LabelSTATE.ForeColor = System.Drawing.Color.Navy;
            this.LabelSTATE.Location = new System.Drawing.Point(78, 203);
            this.LabelSTATE.Name = "LabelSTATE";
            this.LabelSTATE.Size = new System.Drawing.Size(74, 23);
            this.LabelSTATE.TabIndex = 2;
            this.LabelSTATE.Text = "  STATE";
            // 
            // LabelCONTACT
            // 
            this.LabelCONTACT.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.LabelCONTACT.ForeColor = System.Drawing.Color.Navy;
            this.LabelCONTACT.Location = new System.Drawing.Point(31, 239);
            this.LabelCONTACT.Name = "LabelCONTACT";
            this.LabelCONTACT.Size = new System.Drawing.Size(121, 23);
            this.LabelCONTACT.TabIndex = 2;
            this.LabelCONTACT.Text = "CONTACT NO";
            // 
            // LabelLOGIN
            // 
            this.LabelLOGIN.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.LabelLOGIN.ForeColor = System.Drawing.Color.Navy;
            this.LabelLOGIN.Location = new System.Drawing.Point(31, 322);
            this.LabelLOGIN.Name = "LabelLOGIN";
            this.LabelLOGIN.Size = new System.Drawing.Size(121, 23);
            this.LabelLOGIN.TabIndex = 2;
            this.LabelLOGIN.Text = " LOGIN NAME";
            // 
            // LabelFNM
            // 
            this.LabelFNM.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.LabelFNM.ForeColor = System.Drawing.Color.Navy;
            this.LabelFNM.Location = new System.Drawing.Point(31, 131);
            this.LabelFNM.Name = "LabelFNM";
            this.LabelFNM.Size = new System.Drawing.Size(121, 23);
            this.LabelFNM.TabIndex = 2;
            this.LabelFNM.Text = "  FIRST NAME";
            // 
            // LabelLEVEL
            // 
            this.LabelLEVEL.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.LabelLEVEL.ForeColor = System.Drawing.Color.Navy;
            this.LabelLEVEL.Location = new System.Drawing.Point(43, 362);
            this.LabelLEVEL.Name = "LabelLEVEL";
            this.LabelLEVEL.Size = new System.Drawing.Size(109, 23);
            this.LabelLEVEL.TabIndex = 2;
            this.LabelLEVEL.Text = "USER LEVEL";
            // 
            // LabelEMAIL
            // 
            this.LabelEMAIL.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.LabelEMAIL.ForeColor = System.Drawing.Color.Navy;
            this.LabelEMAIL.Location = new System.Drawing.Point(78, 275);
            this.LabelEMAIL.Name = "LabelEMAIL";
            this.LabelEMAIL.Size = new System.Drawing.Size(74, 23);
            this.LabelEMAIL.TabIndex = 2;
            this.LabelEMAIL.Text = "  E-MAIL";
            // 
            // TextBoxLNM
            // 
            this.TextBoxLNM.Location = new System.Drawing.Point(248, 169);
            this.TextBoxLNM.Name = "TextBoxLNM";
            this.TextBoxLNM.Size = new System.Drawing.Size(200, 20);
            this.TextBoxLNM.TabIndex = 3;
            // 
            // TextBoxSTATE
            // 
            this.TextBoxSTATE.Location = new System.Drawing.Point(248, 204);
            this.TextBoxSTATE.Name = "TextBoxSTATE";
            this.TextBoxSTATE.Size = new System.Drawing.Size(200, 20);
            this.TextBoxSTATE.TabIndex = 3;
            // 
            // TextBoxCONTACT
            // 
            this.TextBoxCONTACT.Location = new System.Drawing.Point(248, 240);
            this.TextBoxCONTACT.Name = "TextBoxCONTACT";
            this.TextBoxCONTACT.Size = new System.Drawing.Size(200, 20);
            this.TextBoxCONTACT.TabIndex = 3;
            // 
            // TextBoxEMAIL
            // 
            this.TextBoxEMAIL.Location = new System.Drawing.Point(248, 276);
            this.TextBoxEMAIL.Name = "TextBoxEMAIL";
            this.TextBoxEMAIL.Size = new System.Drawing.Size(200, 20);
            this.TextBoxEMAIL.TabIndex = 3;
            // 
            // TextBoxLOGIN
            // 
            this.TextBoxLOGIN.Location = new System.Drawing.Point(248, 323);
            this.TextBoxLOGIN.Name = "TextBoxLOGIN";
            this.TextBoxLOGIN.Size = new System.Drawing.Size(200, 20);
            this.TextBoxLOGIN.TabIndex = 3;
            // 
            // TextBoxLEVEL
            // 
            this.TextBoxLEVEL.Location = new System.Drawing.Point(248, 363);
            this.TextBoxLEVEL.Name = "TextBoxLEVEL";
            this.TextBoxLEVEL.Size = new System.Drawing.Size(200, 20);
            this.TextBoxLEVEL.TabIndex = 3;
            // 
            // TextBoxFNM
            // 
            this.TextBoxFNM.Location = new System.Drawing.Point(248, 132);
            this.TextBoxFNM.Name = "TextBoxFNM";
            this.TextBoxFNM.Size = new System.Drawing.Size(200, 20);
            this.TextBoxFNM.TabIndex = 3;
            // 
            // ButtonCREATE
            // 
            this.ButtonCREATE.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold);
            this.ButtonCREATE.Location = new System.Drawing.Point(248, 401);
            this.ButtonCREATE.Name = "ButtonCREATE";
            this.ButtonCREATE.Size = new System.Drawing.Size(200, 32);
            this.ButtonCREATE.TabIndex = 4;
            this.ButtonCREATE.Text = "CREATE";
            this.ButtonCREATE.UseVisualStyleBackColor = true;
            this.ButtonCREATE.Click += new System.EventHandler(this.Click_cbaeeb88);
            // 
            // LabelMSG
            // 
            this.LabelMSG.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold);
            this.LabelMSG.ForeColor = System.Drawing.Color.Black;
            this.LabelMSG.Location = new System.Drawing.Point(304, 436);
            this.LabelMSG.Name = "LabelMSG";
            this.LabelMSG.Size = new System.Drawing.Size(82, 23);
            this.LabelMSG.TabIndex = 5;
            this.LabelMSG.Text = "MESSAGE";
            // 
            // EasyUpdator1
            // 
            this.EasyUpdator1.ConnectionID = new System.Guid("1a3e6d80-9bb0-4583-8429-2967b832ae28");
            this.EasyUpdator1.DefaultConnectionString = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\\Users\\rishabh\\OneDrive\\Documents\\" +
                "SOFTWAREMERCHANT.mdb;Mode=ReadWrite;";
            this.EasyUpdator1.DefaultConnectionType = typeof(System.Data.OleDb.OleDbConnection);
            sqlnonequery1.CommandType = LimnorDatabase.enmNonQueryType.Insert;
            sqlnonequery1.MultiRow = false;
            sqlnonequery1.Param_Name = new string[] {
                    "@firstname",
                    "@lastname",
                    "@state",
                    "@contact",
                    "@email",
                    "@loginname",
                    "@level"};
            sqlnonequery1.Param_OleDbType = new System.Data.OleDb.OleDbType[] {
                    System.Data.OleDb.OleDbType.VarWChar,
                    System.Data.OleDb.OleDbType.VarWChar,
                    System.Data.OleDb.OleDbType.VarWChar,
                    System.Data.OleDb.OleDbType.VarWChar,
                    System.Data.OleDb.OleDbType.VarWChar,
                    System.Data.OleDb.OleDbType.VarWChar,
                    System.Data.OleDb.OleDbType.Integer};
            sqlnonequery1.Param_Value = new string[] {
                    "System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c5" +
                        "61934e089|",
                    "System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c5" +
                        "61934e089|",
                    "System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c5" +
                        "61934e089|",
                    "System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c5" +
                        "61934e089|",
                    "System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c5" +
                        "61934e089|",
                    "System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c5" +
                        "61934e089|",
                    "System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c56" +
                        "1934e089|0"};
            sqlnonequery1.SQL = "INSERT INTO [GLASS] ([FIRST NAME],[LAST NAME],[STATE],[CONTACT NO],[E-MAIL],[LOGI" +
                "N NAME],[USER LEVEL])  VALUES (@firstname,@lastname,@state,@contact,@email,@logi" +
                "nname,@level)";
            sqlnonequery1.TableName = "";
            this.EasyUpdator1.ExecutionCommand = sqlnonequery1;
            this.EasyUpdator1.LastInsertID = 0;
            this.EasyUpdator1.Name = "EasyUpdator1";
            // 
            // EasyDataSet1
            // 
            this.EasyDataSet1.ConnectionID = new System.Guid("1a3e6d80-9bb0-4583-8429-2967b832ae28");
            this.EasyDataSet1.DataSetName = "Data_632670bb-cd86-4824-abd7-fddafa4cf860";
            this.EasyDataSet1.DefaultConnectionString = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\\Users\\rishabh\\OneDrive\\Documents\\" +
                "SOFTWAREMERCHANT.mdb;Mode=ReadWrite;";
            this.EasyDataSet1.DefaultConnectionType = typeof(System.Data.OleDb.OleDbConnection);
            this.EasyDataSet1.Description = null;
            this.EasyDataSet1.DynamicParameters = dbparameterlistext1;
            this.EasyDataSet1.Field_DataSize = new int[] {
                    4};
            this.EasyDataSet1.Field_FieldCaption = new string[] {
                    null};
            this.EasyDataSet1.Field_FieldText = new string[] {
                    "[GLASS].[USERiD]"};
            this.EasyDataSet1.Field_FromTableName = new string[] {
                    "GLASS"};
            this.EasyDataSet1.Field_Indexed = new bool[] {
                    true};
            this.EasyDataSet1.Field_IsIdentity = new bool[] {
                    true};
            this.EasyDataSet1.Field_Name = new string[] {
                    "USERiD"};
            this.EasyDataSet1.Field_OleDbType = new System.Data.OleDb.OleDbType[] {
                    System.Data.OleDb.OleDbType.Integer};
            this.EasyDataSet1.Field_ReadOnly = new bool[] {
                    true};
            this.EasyDataSet1.From = "[GLASS]";
            this.EasyDataSet1.GroupBy = null;
            this.EasyDataSet1.Having = null;
            this.EasyDataSet1.IsFieldImage = new bool[] {
                    false};
            this.EasyDataSet1.Limit = null;
            this.EasyDataSet1.Name = "EasyDataSet1";
            this.EasyDataSet1.OrderBy = null;
            this.EasyDataSet1.Param_Name = new string[] {
                    "@loginName"};
            this.EasyDataSet1.Param_OleDbType = new System.Data.OleDb.OleDbType[] {
                    System.Data.OleDb.OleDbType.VarWChar};
            this.EasyDataSet1.Param_Value = new string[] {
                    "System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c5" +
                        "61934e089|"};
            this.EasyDataSet1.TableName = "Table3486311435";
            this.EasyDataSet1.UpdatableTableName = "GLASS";
            this.EasyDataSet1.Where = "[GLASS].[LOGIN NAME] = @loginName";
            // 
            // WebLoginManager1
            // 
            this.WebLoginManager1.ComponentName = "WebLoginManager1";
            this.WebLoginManager1.ConnectionID = new System.Guid("1a3e6d80-9bb0-4583-8429-2967b832ae28");
            this.WebLoginManager1.DefaultConnectionString = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\\Users\\rishabh\\OneDrive\\Documents\\" +
                "SOFTWAREMERCHANT.mdb;Mode=ReadWrite;";
            this.WebLoginManager1.DefaultConnectionType = typeof(System.Data.OleDb.OleDbConnection);
            this.WebLoginManager1.FailedMessageLableId = null;
            this.WebLoginManager1.ID = new System.Guid("5f30d976-45da-4402-8cd0-daf9b4f58c1d");
            this.WebLoginManager1.InactivityMinutes = 0;
            this.WebLoginManager1.LabelToShowLoginFailedMessage = null;
            this.WebLoginManager1.LoginFailedMessage = null;
            this.WebLoginManager1.LoginPermissionFailedMessage = null;
            this.WebLoginManager1.PasswordHash = WindowsUtility.EnumPasswordHash.SHA256;
            this.WebLoginManager1.UserAccountIdFieldName = "USERiD";
            this.WebLoginManager1.UserAccountLevelFieldName = "USER LEVEL";
            this.WebLoginManager1.UserAccountLoginFieldName = "LOGIN NAME";
            this.WebLoginManager1.UserAccountPasswordFieldName = "PASSWORD";
            this.WebLoginManager1.UserAccountResetCodeFieldName = "RESET CODE";
            this.WebLoginManager1.UserAccountResetCodeTimeFieldName = "RESET CODE EXPIRE";
            this.WebLoginManager1.UserAccountSaltFieldName = "SALT";
            this.WebLoginManager1.UserAccountTableName = "GLASS";
            // 
            // CreateNewUser
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.ClientSize = new System.Drawing.Size(472, 478);
            this.Controls.Add(this.Label1);
            this.Controls.Add(this.PictureBox1);
            this.Controls.Add(this.LabelLNM);
            this.Controls.Add(this.LabelSTATE);
            this.Controls.Add(this.LabelCONTACT);
            this.Controls.Add(this.LabelLOGIN);
            this.Controls.Add(this.LabelFNM);
            this.Controls.Add(this.LabelLEVEL);
            this.Controls.Add(this.LabelEMAIL);
            this.Controls.Add(this.TextBoxLNM);
            this.Controls.Add(this.TextBoxSTATE);
            this.Controls.Add(this.TextBoxCONTACT);
            this.Controls.Add(this.TextBoxEMAIL);
            this.Controls.Add(this.TextBoxLOGIN);
            this.Controls.Add(this.TextBoxLEVEL);
            this.Controls.Add(this.TextBoxFNM);
            this.Controls.Add(this.ButtonCREATE);
            this.Controls.Add(this.LabelMSG);
            this.DrawingLayerList = ((Limnor.Drawing2D.DrawingLayerHeaderList)(resources.GetObject("$this.DrawingLayerList")));
            this.Name = "CreateNewUser";
            this.Text = "CreateNewUser";
            EasyDataSet1.CreateDataTable();
            EasyDataSet1.Query();
            WebLoginManager1.CreateDataTable();
            ((System.ComponentModel.ISupportInitialize)(EasyDataSet1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(PictureBox1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        private void Click_cbaeeb88(object sender, System.EventArgs e)
        {
            if ((string.IsNullOrEmpty(this.TextBoxLOGIN.Text) || string.IsNullOrEmpty(this.TextBoxEMAIL.Text)))
            {
                return;
            }
            this.EasyDataSet1.QueryWithParameterValues(this.TextBoxLOGIN.Text);
            if (this.EasyDataSet1.HasData)
            {
                return;
            }
            this.EasyUpdator1.ExecuteWithParameterValues(this.TextBoxFNM.Text, this.TextBoxLNM.Text, this.TextBoxSTATE.Text, this.TextBoxCONTACT.Text, this.TextBoxEMAIL.Text, this.TextBoxLOGIN.Text, this.TextBoxLEVEL.Text);
            this.NewPassword = WindowsUtility.WinUtil.GetRandomString(10);
            this.WebLoginManager1.ResetPassword(this.TextBoxLOGIN.Text, this.NewPassword);
            this.MailSender1.Body = string.Format(System.Globalization.CultureInfo.InvariantCulture, "{0}{1}{2}{3}{4}", new object[] {
                        "Your account is created.Login name is ",
                        this.TextBoxLOGIN.Text,
                        "password is",
                        this.NewPassword,
                        ".You need to change your password as soon as possible."});
            this.MailSender1.AddRecipient(this.TextBoxEMAIL.Text, null, Limnor.Net.EnumCharEncode.Default);
            this.MailSender1.Send();
            this.MailSender1.ClearRecipients();
            System.Windows.Forms.MessageBox.Show(this, "A new user account is created.");
        }
        protected override void Dispose(bool disposing)
        {
            if ((disposing 
                        && (components != null)))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}
