//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Limnor Studio.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefaultNamespace
{
    using System;
    using System.Xml;
    using System.Text;
    using System.Collections.Generic;
    using Limnor.Drawing2D;
    using System.Drawing;
    using System.Windows.Forms;
    using LimnorDatabase;
    
    public class changePassword : Limnor.Drawing2D.DrawingPage
    {
        protected internal System.Windows.Forms.Label LabelCURRPASS;
        protected internal System.Windows.Forms.Label LABELNEWPASS;
        protected internal System.Windows.Forms.Label LabelCONFRPASS;
        protected internal System.Windows.Forms.Label LabelLOGIN;
        protected internal System.Windows.Forms.TextBox TextBoxCURRPASS;
        protected internal System.Windows.Forms.TextBox TextBoxNEWPASS;
        protected internal System.Windows.Forms.TextBox TextBoxCONFPASS;
        protected internal System.Windows.Forms.TextBox TextBoxLOGIN;
        protected internal System.Windows.Forms.Button ButtoNSUBMIT;
        protected internal System.Windows.Forms.Label LabelCHHEAD;
        protected internal System.Windows.Forms.Label LabelMSG;
        protected internal LimnorDatabase.WebLoginManager WebLoginManager1;
        private System.ComponentModel.IContainer components;
        private static changePassword _DefaultForm;
        private bool valueOfPasswordChanged = false;
        /// <summary>
        /// </summary>
        public changePassword()
        {
            this.InitializeComponent();
        }
        public static changePassword DefaultForm
        {
            get
            {
                if (((_DefaultForm == null) 
                            || (_DefaultForm.IsDisposed || _DefaultForm.Disposing)))
                {
                    _DefaultForm = new changePassword();
                }
                return _DefaultForm;
            }
        }
        public virtual bool PasswordChanged
        {
            get
            {
                return this.valueOfPasswordChanged;
            }
            set
            {
                this.valueOfPasswordChanged = value;
            }
        }
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(changePassword));
            this.LabelCURRPASS = new System.Windows.Forms.Label();
            this.LABELNEWPASS = new System.Windows.Forms.Label();
            this.LabelCONFRPASS = new System.Windows.Forms.Label();
            this.LabelLOGIN = new System.Windows.Forms.Label();
            this.TextBoxCURRPASS = new System.Windows.Forms.TextBox();
            this.TextBoxNEWPASS = new System.Windows.Forms.TextBox();
            this.TextBoxCONFPASS = new System.Windows.Forms.TextBox();
            this.TextBoxLOGIN = new System.Windows.Forms.TextBox();
            this.ButtoNSUBMIT = new System.Windows.Forms.Button();
            this.LabelCHHEAD = new System.Windows.Forms.Label();
            this.LabelMSG = new System.Windows.Forms.Label();
            this.components = new System.ComponentModel.Container();
            this.WebLoginManager1 = new LimnorDatabase.WebLoginManager(this.components);
            this.SuspendLayout();
            // 
            // LabelCURRPASS
            // 
            this.LabelCURRPASS.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.LabelCURRPASS.ForeColor = System.Drawing.Color.Navy;
            this.LabelCURRPASS.Location = new System.Drawing.Point(25, 103);
            this.LabelCURRPASS.Name = "LabelCURRPASS";
            this.LabelCURRPASS.Size = new System.Drawing.Size(194, 23);
            this.LabelCURRPASS.TabIndex = 0;
            this.LabelCURRPASS.Text = "CURRENT PASSWORD";
            // 
            // LABELNEWPASS
            // 
            this.LABELNEWPASS.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.LABELNEWPASS.ForeColor = System.Drawing.Color.Navy;
            this.LABELNEWPASS.Location = new System.Drawing.Point(68, 177);
            this.LABELNEWPASS.Name = "LABELNEWPASS";
            this.LABELNEWPASS.Size = new System.Drawing.Size(151, 23);
            this.LABELNEWPASS.TabIndex = 0;
            this.LABELNEWPASS.Text = "NEW PASSWORD";
            // 
            // LabelCONFRPASS
            // 
            this.LabelCONFRPASS.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.LabelCONFRPASS.ForeColor = System.Drawing.Color.Navy;
            this.LabelCONFRPASS.Location = new System.Drawing.Point(25, 223);
            this.LabelCONFRPASS.Name = "LabelCONFRPASS";
            this.LabelCONFRPASS.Size = new System.Drawing.Size(194, 23);
            this.LabelCONFRPASS.TabIndex = 0;
            this.LabelCONFRPASS.Text = "CONFIRM PASSWORD";
            // 
            // LabelLOGIN
            // 
            this.LabelLOGIN.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.LabelLOGIN.ForeColor = System.Drawing.Color.Navy;
            this.LabelLOGIN.Location = new System.Drawing.Point(106, 55);
            this.LabelLOGIN.Name = "LabelLOGIN";
            this.LabelLOGIN.Size = new System.Drawing.Size(113, 23);
            this.LabelLOGIN.TabIndex = 0;
            this.LabelLOGIN.Text = "LOGIN NAME";
            // 
            // TextBoxCURRPASS
            // 
            this.TextBoxCURRPASS.Location = new System.Drawing.Point(259, 106);
            this.TextBoxCURRPASS.Name = "TextBoxCURRPASS";
            this.TextBoxCURRPASS.Size = new System.Drawing.Size(190, 20);
            this.TextBoxCURRPASS.TabIndex = 1;
            // 
            // TextBoxNEWPASS
            // 
            this.TextBoxNEWPASS.Location = new System.Drawing.Point(259, 178);
            this.TextBoxNEWPASS.Name = "TextBoxNEWPASS";
            this.TextBoxNEWPASS.Size = new System.Drawing.Size(190, 20);
            this.TextBoxNEWPASS.TabIndex = 1;
            // 
            // TextBoxCONFPASS
            // 
            this.TextBoxCONFPASS.Location = new System.Drawing.Point(259, 226);
            this.TextBoxCONFPASS.Name = "TextBoxCONFPASS";
            this.TextBoxCONFPASS.Size = new System.Drawing.Size(190, 20);
            this.TextBoxCONFPASS.TabIndex = 1;
            // 
            // TextBoxLOGIN
            // 
            this.TextBoxLOGIN.Location = new System.Drawing.Point(259, 58);
            this.TextBoxLOGIN.Name = "TextBoxLOGIN";
            this.TextBoxLOGIN.Size = new System.Drawing.Size(190, 20);
            this.TextBoxLOGIN.TabIndex = 1;
            // 
            // ButtoNSUBMIT
            // 
            this.ButtoNSUBMIT.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.ButtoNSUBMIT.ForeColor = System.Drawing.Color.Navy;
            this.ButtoNSUBMIT.Location = new System.Drawing.Point(259, 268);
            this.ButtoNSUBMIT.Name = "ButtoNSUBMIT";
            this.ButtoNSUBMIT.Size = new System.Drawing.Size(190, 31);
            this.ButtoNSUBMIT.TabIndex = 2;
            this.ButtoNSUBMIT.Text = "SUBMIT";
            this.ButtoNSUBMIT.UseVisualStyleBackColor = true;
            this.ButtoNSUBMIT.Click += new System.EventHandler(this.Click_a9d460fd);
            // 
            // LabelCHHEAD
            // 
            this.LabelCHHEAD.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.LabelCHHEAD.ForeColor = System.Drawing.Color.Black;
            this.LabelCHHEAD.Location = new System.Drawing.Point(259, 9);
            this.LabelCHHEAD.Name = "LabelCHHEAD";
            this.LabelCHHEAD.Size = new System.Drawing.Size(190, 23);
            this.LabelCHHEAD.TabIndex = 3;
            this.LabelCHHEAD.Text = "CHANGE PASSWORD";
            // 
            // LabelMSG
            // 
            this.LabelMSG.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold);
            this.LabelMSG.Location = new System.Drawing.Point(313, 316);
            this.LabelMSG.Name = "LabelMSG";
            this.LabelMSG.Size = new System.Drawing.Size(81, 23);
            this.LabelMSG.TabIndex = 4;
            this.LabelMSG.Text = "MESSAGE";
            // 
            // WebLoginManager1
            // 
            this.WebLoginManager1.ComponentName = "WebLoginManager1";
            this.WebLoginManager1.ConnectionID = new System.Guid("1a3e6d80-9bb0-4583-8429-2967b832ae28");
            this.WebLoginManager1.DefaultConnectionString = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\\Users\\rishabh\\OneDrive\\Documents\\" +
                "SOFTWAREMERCHANT.mdb;Mode=ReadWrite;";
            this.WebLoginManager1.DefaultConnectionType = typeof(System.Data.OleDb.OleDbConnection);
            this.WebLoginManager1.FailedMessageLableId = "LabelMSG";
            this.WebLoginManager1.ID = new System.Guid("a6fba34f-2cc3-4182-96ff-96b09992880c");
            this.WebLoginManager1.InactivityMinutes = 10;
            this.WebLoginManager1.LabelToShowLoginFailedMessage = this.LabelMSG;
            this.WebLoginManager1.LoginFailedMessage = null;
            this.WebLoginManager1.LoginPermissionFailedMessage = null;
            this.WebLoginManager1.PasswordHash = WindowsUtility.EnumPasswordHash.SHA256;
            this.WebLoginManager1.UserAccountIdFieldName = "USERiD";
            this.WebLoginManager1.UserAccountLevelFieldName = "USER LEVEL";
            this.WebLoginManager1.UserAccountLoginFieldName = "LOGIN NAME";
            this.WebLoginManager1.UserAccountPasswordFieldName = "PASSWORD";
            this.WebLoginManager1.UserAccountResetCodeFieldName = "RESET CODE";
            this.WebLoginManager1.UserAccountResetCodeTimeFieldName = "RESET CODE EXPIRE";
            this.WebLoginManager1.UserAccountSaltFieldName = "SALT";
            this.WebLoginManager1.UserAccountTableName = "GLASS";
            // 
            // changePassword
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.ClientSize = new System.Drawing.Size(477, 348);
            this.Controls.Add(this.LabelCURRPASS);
            this.Controls.Add(this.LABELNEWPASS);
            this.Controls.Add(this.LabelCONFRPASS);
            this.Controls.Add(this.LabelLOGIN);
            this.Controls.Add(this.TextBoxCURRPASS);
            this.Controls.Add(this.TextBoxNEWPASS);
            this.Controls.Add(this.TextBoxCONFPASS);
            this.Controls.Add(this.TextBoxLOGIN);
            this.Controls.Add(this.ButtoNSUBMIT);
            this.Controls.Add(this.LabelCHHEAD);
            this.Controls.Add(this.LabelMSG);
            this.DrawingLayerList = ((Limnor.Drawing2D.DrawingLayerHeaderList)(resources.GetObject("$this.DrawingLayerList")));
            this.Name = "changePassword";
            this.Text = "changePassword";
            WebLoginManager1.CreateDataTable();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        private void Click_a9d460fd(object sender, System.EventArgs e)
        {
            if ((string.IsNullOrEmpty(this.TextBoxNEWPASS.Text) 
                        || (string.CompareOrdinal(this.TextBoxNEWPASS.Text, this.TextBoxCONFPASS.Text) != 0)))
            {
                System.Windows.Forms.MessageBox.Show(this, "New password cannot be empty and must match with retyped password.");
            }
            if ((string.IsNullOrEmpty(this.TextBoxNEWPASS.Text) 
                        || (string.CompareOrdinal(this.TextBoxNEWPASS.Text, this.TextBoxCONFPASS.Text) != 0)))
            {
                return;
            }
            this.PasswordChanged = this.WebLoginManager1.ChangePassword(this.TextBoxLOGIN.Text, this.TextBoxCURRPASS.Text, this.TextBoxNEWPASS.Text);
            if ((this.PasswordChanged == false))
            {
                System.Windows.Forms.MessageBox.Show(this, "Invalid user credential");
            }
            if (this.PasswordChanged)
            {
                System.Windows.Forms.MessageBox.Show(this, "Password Changed");
            }
        }
        protected override void Dispose(bool disposing)
        {
            if ((disposing 
                        && (components != null)))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}
