//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Limnor Studio.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefaultNamespace
{
    using System;
    using System.Xml;
    using System.Text;
    using System.Collections.Generic;
    using Limnor.Drawing2D;
    using System.Windows.Forms;
    using System.Drawing;
    
    public class formhome : Limnor.Drawing2D.DrawingPage
    {
        protected internal System.Windows.Forms.Label LABELHEAD;
        protected internal System.Windows.Forms.PictureBox PictureBox1;
        protected internal System.Windows.Forms.Button BTNCHPASS;
        protected internal System.Windows.Forms.Button BTNNEWUSER;
        protected internal System.Windows.Forms.Button BTNRESETCODE;
        protected internal System.Windows.Forms.Button BTNRESETPASS;
        protected internal System.Windows.Forms.Button BTNFORM3;
        protected internal System.Windows.Forms.Button BTNUSERADMIN;
        protected internal System.Windows.Forms.Button BTNFORM2;
        private static formhome _DefaultForm;
        /// <summary>
        /// </summary>
        public formhome()
        {
            this.InitializeComponent();
        }
        public static formhome DefaultForm
        {
            get
            {
                if (((_DefaultForm == null) 
                            || (_DefaultForm.IsDisposed || _DefaultForm.Disposing)))
                {
                    _DefaultForm = new formhome();
                }
                return _DefaultForm;
            }
        }
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(formhome));
            this.LABELHEAD = new System.Windows.Forms.Label();
            this.PictureBox1 = new System.Windows.Forms.PictureBox();
            this.BTNCHPASS = new System.Windows.Forms.Button();
            this.BTNNEWUSER = new System.Windows.Forms.Button();
            this.BTNRESETCODE = new System.Windows.Forms.Button();
            this.BTNRESETPASS = new System.Windows.Forms.Button();
            this.BTNFORM3 = new System.Windows.Forms.Button();
            this.BTNUSERADMIN = new System.Windows.Forms.Button();
            this.BTNFORM2 = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(PictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // LABELHEAD
            // 
            this.LABELHEAD.Font = new System.Drawing.Font("Algerian", 12F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.LABELHEAD.ForeColor = System.Drawing.Color.Navy;
            this.LABELHEAD.Location = new System.Drawing.Point(67, 33);
            this.LABELHEAD.Name = "LABELHEAD";
            this.LABELHEAD.Size = new System.Drawing.Size(262, 23);
            this.LABELHEAD.TabIndex = 0;
            this.LABELHEAD.Text = "PERMISSION CONTROL SAMPLE";
            // 
            // PictureBox1
            // 
            this.PictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("PictureBox1.Image")));
            this.PictureBox1.Location = new System.Drawing.Point(139, 59);
            this.PictureBox1.Name = "PictureBox1";
            this.PictureBox1.Size = new System.Drawing.Size(100, 50);
            this.PictureBox1.TabIndex = 1;
            this.PictureBox1.TabStop = false;
            // 
            // BTNCHPASS
            // 
            this.BTNCHPASS.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Bold);
            this.BTNCHPASS.ForeColor = System.Drawing.Color.Navy;
            this.BTNCHPASS.Location = new System.Drawing.Point(248, 146);
            this.BTNCHPASS.Name = "BTNCHPASS";
            this.BTNCHPASS.Size = new System.Drawing.Size(209, 26);
            this.BTNCHPASS.TabIndex = 2;
            this.BTNCHPASS.Text = "CHANGE PASSWORD";
            this.BTNCHPASS.UseVisualStyleBackColor = true;
            this.BTNCHPASS.Click += new System.EventHandler(this.Click_d96b4b6a);
            // 
            // BTNNEWUSER
            // 
            this.BTNNEWUSER.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Bold);
            this.BTNNEWUSER.ForeColor = System.Drawing.Color.Navy;
            this.BTNNEWUSER.Location = new System.Drawing.Point(12, 202);
            this.BTNNEWUSER.Name = "BTNNEWUSER";
            this.BTNNEWUSER.Size = new System.Drawing.Size(209, 26);
            this.BTNNEWUSER.TabIndex = 2;
            this.BTNNEWUSER.Text = "CREATE NEW USER";
            this.BTNNEWUSER.UseVisualStyleBackColor = true;
            this.BTNNEWUSER.Click += new System.EventHandler(this.Click_55a639eb);
            // 
            // BTNRESETCODE
            // 
            this.BTNRESETCODE.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Bold);
            this.BTNRESETCODE.ForeColor = System.Drawing.Color.Navy;
            this.BTNRESETCODE.Location = new System.Drawing.Point(248, 202);
            this.BTNRESETCODE.Name = "BTNRESETCODE";
            this.BTNRESETCODE.Size = new System.Drawing.Size(209, 26);
            this.BTNRESETCODE.TabIndex = 2;
            this.BTNRESETCODE.Text = "CREATE RESET CODE";
            this.BTNRESETCODE.UseVisualStyleBackColor = true;
            this.BTNRESETCODE.Click += new System.EventHandler(this.Click_13a67931);
            // 
            // BTNRESETPASS
            // 
            this.BTNRESETPASS.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Bold);
            this.BTNRESETPASS.ForeColor = System.Drawing.Color.Navy;
            this.BTNRESETPASS.Location = new System.Drawing.Point(139, 324);
            this.BTNRESETPASS.Name = "BTNRESETPASS";
            this.BTNRESETPASS.Size = new System.Drawing.Size(209, 26);
            this.BTNRESETPASS.TabIndex = 2;
            this.BTNRESETPASS.Text = "RESET PASSWORD";
            this.BTNRESETPASS.UseVisualStyleBackColor = true;
            this.BTNRESETPASS.Click += new System.EventHandler(this.Click_dd09f754);
            // 
            // BTNFORM3
            // 
            this.BTNFORM3.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Bold);
            this.BTNFORM3.ForeColor = System.Drawing.Color.Navy;
            this.BTNFORM3.Location = new System.Drawing.Point(248, 268);
            this.BTNFORM3.Name = "BTNFORM3";
            this.BTNFORM3.Size = new System.Drawing.Size(209, 26);
            this.BTNFORM3.TabIndex = 2;
            this.BTNFORM3.Text = "FORM3";
            this.BTNFORM3.UseVisualStyleBackColor = true;
            this.BTNFORM3.Click += new System.EventHandler(this.Click_ec00f670);
            // 
            // BTNUSERADMIN
            // 
            this.BTNUSERADMIN.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Bold);
            this.BTNUSERADMIN.ForeColor = System.Drawing.Color.Navy;
            this.BTNUSERADMIN.Location = new System.Drawing.Point(12, 146);
            this.BTNUSERADMIN.Name = "BTNUSERADMIN";
            this.BTNUSERADMIN.Size = new System.Drawing.Size(209, 26);
            this.BTNUSERADMIN.TabIndex = 2;
            this.BTNUSERADMIN.Text = "USER LOGIN";
            this.BTNUSERADMIN.UseVisualStyleBackColor = true;
            this.BTNUSERADMIN.Click += new System.EventHandler(this.Click_2c6d928e);
            // 
            // BTNFORM2
            // 
            this.BTNFORM2.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Bold);
            this.BTNFORM2.ForeColor = System.Drawing.Color.Navy;
            this.BTNFORM2.Location = new System.Drawing.Point(12, 268);
            this.BTNFORM2.Name = "BTNFORM2";
            this.BTNFORM2.Size = new System.Drawing.Size(209, 26);
            this.BTNFORM2.TabIndex = 3;
            this.BTNFORM2.Text = "FORM2";
            this.BTNFORM2.UseVisualStyleBackColor = true;
            this.BTNFORM2.Click += new System.EventHandler(this.Click_60c7cd57);
            // 
            // formhome
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.ClientSize = new System.Drawing.Size(469, 387);
            this.Controls.Add(this.LABELHEAD);
            this.Controls.Add(this.PictureBox1);
            this.Controls.Add(this.BTNCHPASS);
            this.Controls.Add(this.BTNNEWUSER);
            this.Controls.Add(this.BTNRESETCODE);
            this.Controls.Add(this.BTNRESETPASS);
            this.Controls.Add(this.BTNFORM3);
            this.Controls.Add(this.BTNUSERADMIN);
            this.Controls.Add(this.BTNFORM2);
            this.DrawingLayerList = ((Limnor.Drawing2D.DrawingLayerHeaderList)(resources.GetObject("$this.DrawingLayerList")));
            this.Name = "formhome";
            this.Text = "Main form";
            ((System.ComponentModel.ISupportInitialize)(PictureBox1)).EndInit();
            this.ResumeLayout(false);
        }
        private void Click_2c6d928e(object sender, System.EventArgs e)
        {
            UserLogin.DefaultForm.Show(this);
        }
        private void Click_d96b4b6a(object sender, System.EventArgs e)
        {
            changePassword.DefaultForm.Show(this);
        }
        private void Click_55a639eb(object sender, System.EventArgs e)
        {
            CreateNewUser.DefaultForm.Show(this);
        }
        private void Click_13a67931(object sender, System.EventArgs e)
        {
            CreateResetCode.DefaultForm.Show(this);
        }
        private void Click_ec00f670(object sender, System.EventArgs e)
        {
            Form3.DefaultForm.Show(this);
        }
        private void Click_60c7cd57(object sender, System.EventArgs e)
        {
            Form2.DefaultForm.Show(this);
        }
        private void Click_dd09f754(object sender, System.EventArgs e)
        {
            ResetPassword.DefaultForm.Show(this);
        }
    }
}
