//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Limnor Studio.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefaultNamespace
{
    using System;
    using System.Xml;
    using System.Text;
    using System.Collections.Generic;
    using Limnor.Drawing2D;
    using System.Windows.Forms;
    using System.Drawing;
    
    public class Form2 : Limnor.Drawing2D.DrawingPage
    {
        protected internal System.Windows.Forms.Label Labelhead;
        protected internal System.Windows.Forms.PictureBox PBCUT;
        protected internal System.Windows.Forms.PictureBox PBPURCH;
        protected internal System.Windows.Forms.PictureBox PBGRIND;
        protected internal System.Windows.Forms.CheckBox CBGRIND;
        protected internal System.Windows.Forms.CheckBox CBPURCH;
        protected internal System.Windows.Forms.CheckBox CBCUT;
        protected internal System.Windows.Forms.Button BTNSAVE;
        private static Form2 _DefaultForm;
        /// <summary>
        /// </summary>
        public Form2()
        {
            this.InitializeComponent();
            this.SetLoginManagerID(new System.Guid("dfc298bb-0960-49bf-b1ec-eb260632a388"));
        }
        public static Form2 DefaultForm
        {
            get
            {
                if (((_DefaultForm == null) 
                            || (_DefaultForm.IsDisposed || _DefaultForm.Disposing)))
                {
                    _DefaultForm = new Form2();
                }
                return _DefaultForm;
            }
        }
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form2));
            this.Labelhead = new System.Windows.Forms.Label();
            this.PBCUT = new System.Windows.Forms.PictureBox();
            this.PBPURCH = new System.Windows.Forms.PictureBox();
            this.PBGRIND = new System.Windows.Forms.PictureBox();
            this.CBGRIND = new System.Windows.Forms.CheckBox();
            this.CBPURCH = new System.Windows.Forms.CheckBox();
            this.CBCUT = new System.Windows.Forms.CheckBox();
            this.BTNSAVE = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(PBGRIND)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(PBPURCH)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(PBCUT)).BeginInit();
            this.SuspendLayout();
            // 
            // Labelhead
            // 
            this.Labelhead.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.Labelhead.ForeColor = System.Drawing.Color.Navy;
            this.Labelhead.Location = new System.Drawing.Point(119, 41);
            this.Labelhead.Name = "Labelhead";
            this.Labelhead.Size = new System.Drawing.Size(153, 23);
            this.Labelhead.TabIndex = 0;
            this.Labelhead.Text = "TYPES OF TASK";
            // 
            // PBCUT
            // 
            this.PBCUT.Image = ((System.Drawing.Image)(resources.GetObject("PBCUT.Image")));
            this.PBCUT.Location = new System.Drawing.Point(239, 108);
            this.PBCUT.Name = "PBCUT";
            this.PBCUT.Size = new System.Drawing.Size(76, 63);
            this.PBCUT.TabIndex = 1;
            this.PBCUT.TabStop = false;
            // 
            // PBPURCH
            // 
            this.PBPURCH.Image = ((System.Drawing.Image)(resources.GetObject("PBPURCH.Image")));
            this.PBPURCH.Location = new System.Drawing.Point(136, 211);
            this.PBPURCH.Name = "PBPURCH";
            this.PBPURCH.Size = new System.Drawing.Size(103, 63);
            this.PBPURCH.TabIndex = 1;
            this.PBPURCH.TabStop = false;
            // 
            // PBGRIND
            // 
            this.PBGRIND.Image = ((System.Drawing.Image)(resources.GetObject("PBGRIND.Image")));
            this.PBGRIND.Location = new System.Drawing.Point(37, 108);
            this.PBGRIND.Name = "PBGRIND";
            this.PBGRIND.Size = new System.Drawing.Size(93, 63);
            this.PBGRIND.TabIndex = 1;
            this.PBGRIND.TabStop = false;
            // 
            // CBGRIND
            // 
            this.CBGRIND.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold);
            this.CBGRIND.Location = new System.Drawing.Point(37, 177);
            this.CBGRIND.Name = "CBGRIND";
            this.CBGRIND.Size = new System.Drawing.Size(104, 24);
            this.CBGRIND.TabIndex = 2;
            this.CBGRIND.Text = "GRINDING";
            this.CBGRIND.UseVisualStyleBackColor = true;
            // 
            // CBPURCH
            // 
            this.CBPURCH.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold);
            this.CBPURCH.Location = new System.Drawing.Point(135, 280);
            this.CBPURCH.Name = "CBPURCH";
            this.CBPURCH.Size = new System.Drawing.Size(111, 24);
            this.CBPURCH.TabIndex = 2;
            this.CBPURCH.Text = "PURCHASE";
            this.CBPURCH.UseVisualStyleBackColor = true;
            // 
            // CBCUT
            // 
            this.CBCUT.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold);
            this.CBCUT.Location = new System.Drawing.Point(239, 177);
            this.CBCUT.Name = "CBCUT";
            this.CBCUT.Size = new System.Drawing.Size(104, 24);
            this.CBCUT.TabIndex = 2;
            this.CBCUT.Text = "CUTTING";
            this.CBCUT.UseVisualStyleBackColor = true;
            // 
            // BTNSAVE
            // 
            this.BTNSAVE.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold);
            this.BTNSAVE.Location = new System.Drawing.Point(136, 324);
            this.BTNSAVE.Name = "BTNSAVE";
            this.BTNSAVE.Size = new System.Drawing.Size(103, 36);
            this.BTNSAVE.TabIndex = 3;
            this.BTNSAVE.Text = "SUBMIT";
            this.BTNSAVE.UseVisualStyleBackColor = true;
            this.BTNSAVE.Click += new System.EventHandler(this.Click_9537b6ae);
            // 
            // Form2
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.ClientSize = new System.Drawing.Size(407, 372);
            this.Controls.Add(this.Labelhead);
            this.Controls.Add(this.PBCUT);
            this.Controls.Add(this.PBPURCH);
            this.Controls.Add(this.PBGRIND);
            this.Controls.Add(this.CBGRIND);
            this.Controls.Add(this.CBPURCH);
            this.Controls.Add(this.CBCUT);
            this.Controls.Add(this.BTNSAVE);
            this.DrawingLayerList = ((Limnor.Drawing2D.DrawingLayerHeaderList)(resources.GetObject("$this.DrawingLayerList")));
            this.LoginPageId = ((uint)(846243786u));
            this.Name = "Form2";
            this.Text = "Form2";
            ((System.ComponentModel.ISupportInitialize)(PBGRIND)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(PBPURCH)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(PBCUT)).EndInit();
            this.ResumeLayout(false);
        }
        protected override void OnShowUserLogonDialog()
        {
            UserLogin.DefaultForm.ShowDialog(this);
        }
        private void Click_9537b6ae(object sender, System.EventArgs e)
        {
            System.Windows.Forms.MessageBox.Show(this, "TASK ADDED SUCCESSFULLY");
        }
    }
}
